plugins {
    id 'java-library'
}

group = 'com.sovdee'

repositories {
    mavenCentral()
}

dependencies {
    api "org.joml:joml:${jomlVersion}"
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(21))
}
