package com.sovdee.shapes.shapes;

import com.sovdee.shapes.sampling.SamplingStyle;
import org.joml.Vector3d;

import java.util.ArrayList;
import java.util.List;

/**
 * A circle (or cylinder when {@code height > 0}) centred at the local origin in the XZ plane.
 * <p>
 * With {@code height == 0} the three generation modes produce:
 * <ul>
 *   <li>{@link #generateOutline} — a ring of points at the given radius</li>
 *   <li>{@link #generateSurface} — a filled disc (solid circle)</li>
 *   <li>{@link #generateFilled}  — same as surface for a flat shape</li>
 * </ul>
 * With {@code height > 0} the modes produce:
 * <ul>
 *   <li>{@link #generateOutline} — two rings at Y = 0 and Y = height, connected by vertical lines</li>
 *   <li>{@link #generateSurface} — a full cylinder (two discs + wall)</li>
 *   <li>{@link #generateFilled}  — a solid cylindrical volume</li>
 * </ul>
 * <p>
 * The protected field {@code cutoffAngle} is inherited by {@link Arc} to limit the angular span.
 * In a plain {@code Circle} this is always {@code 2π}. All angles are measured from the positive
 * X axis in the XZ plane.
 * <p>
 * {@code Circle} implements both {@link RadialShape} and {@link LWHShape}; the {@code length} and
 * {@code width} dimensions are not meaningful for a circle and return/accept {@code 0}. Only
 * {@code height} is active via {@link LWHShape}.
 */
public class Circle extends AbstractShape implements RadialShape, LWHShape {

    private double radius;
    protected double cutoffAngle;
    private double height;

    /**
     * Creates a flat circle (height = 0) with the given radius.
     *
     * @param radius the radius of the circle; clamped to at least {@link Shape#EPSILON}
     */
    public Circle(double radius) {
        this(radius, 0);
    }

    /**
     * Creates a circle or cylinder with the given radius and height.
     * A height of {@code 0} produces a flat 2-D circle.
     *
     * @param radius the radius; clamped to at least {@link Shape#EPSILON}
     * @param height the vertical extent; clamped to {@code >= 0}
     */
    public Circle(double radius, double height) {
        super();
        this.radius = Math.max(radius, Shape.EPSILON);
        this.height = Math.max(height, 0);
        this.cutoffAngle = 2 * Math.PI;
    }

    // --- Static calculation methods ---

    /**
     * Appends points evenly spaced along a circular arc of the given {@code radius} in the XZ
     * plane. The angular step is {@code density / radius} radians, so arc-length spacing between
     * consecutive points equals approximately {@code density}.
     *
     * @param points      the list to append to; must not be null
     * @param radius      the radius of the circle
     * @param density     the desired arc-length spacing between points
     * @param cutoffAngle the angular span to cover, in radians ({@code [0, 2π]})
     */
    public static void calculateCircle(List<Vector3d> points, double radius, double density, double cutoffAngle) {
        double stepSize = density / radius;
        if (points instanceof ArrayList<?> al)
            al.ensureCapacity(points.size() + (int) (cutoffAngle / stepSize) + 1);
        for (double theta = 0; theta < cutoffAngle; theta += stepSize) {
            points.add(new Vector3d(Math.cos(theta) * radius, 0, Math.sin(theta) * radius));
        }
    }

    /**
     * Appends points filling the area of a disc sector in the XZ plane by stacking concentric
     * rings from {@code density} to {@code radius} (inclusive) at intervals of {@code density}.
     * Each ring is generated by {@link #calculateCircle}.
     *
     * @param points      the list to append to; must not be null
     * @param radius      the outer radius of the disc
     * @param density     the desired spacing between points and between concentric rings
     * @param cutoffAngle the angular span of the sector, in radians ({@code [0, 2π]})
     */
    public static void calculateDisc(List<Vector3d> points, double radius, double density, double cutoffAngle) {
        if (points instanceof ArrayList<?> al)
            al.ensureCapacity(points.size() + (int) (cutoffAngle * radius * radius / (density * density * Math.PI)));
        for (double subRadius = density; subRadius < radius; subRadius += density) {
            calculateCircle(points, subRadius, density, cutoffAngle);
        }
        calculateCircle(points, radius, density, cutoffAngle);
    }

    /**
     * Appends points filling a cylindrical (or wedge-cylinder) volume. The method generates:
     * <ol>
     *   <li>A bottom disc at Y = 0.</li>
     *   <li>A top disc at Y = {@code height} (copied from the bottom disc).</li>
     *   <li>The curved wall, filled vertically via {@link #fillVertically}.</li>
     * </ol>
     *
     * @param points      the list to append to; must not be null
     * @param radius      the radius of the cylinder
     * @param height      the height of the cylinder; must be positive
     * @param density     the desired spacing between points
     * @param cutoffAngle the angular span of the cylinder sector, in radians ({@code [0, 2π]})
     */
    public static void calculateCylinder(List<Vector3d> points, double radius, double height, double density, double cutoffAngle) {
        // Bottom disc
        int discStart = points.size();
        calculateDisc(points, radius, density, cutoffAngle);
        int discEnd = points.size();
        // Top disc - copy bottom disc at height
        for (int i = discStart; i < discEnd; i++) {
            Vector3d v = points.get(i);
            points.add(new Vector3d(v.x, height, v.z));
        }
        // Wall
        int wallStart = points.size();
        calculateCircle(points, radius, density, cutoffAngle);
        fillVertically(points, wallStart, height, density);
    }

    // --- Generation methods ---

    @Override
    public void generateOutline(List<Vector3d> points, double density) {
        int start = points.size();
        calculateCircle(points, radius, density, cutoffAngle);
        if (height != 0) {
            fillVertically(points, start, height, density);
        }
    }

    @Override
    public void generateSurface(List<Vector3d> points, double density) {
        if (height != 0)
            calculateCylinder(points, radius, height, density, cutoffAngle);
        else
            calculateDisc(points, radius, density, cutoffAngle);
    }

    @Override
    public void generateFilled(List<Vector3d> points, double density) {
        int start = points.size();
        calculateDisc(points, radius, density, cutoffAngle);
        if (height != 0) {
            fillVertically(points, start, height, density);
        }
    }

    @Override
    public double computeDensity(SamplingStyle style, int targetPointCount) {
        int count = Math.max(targetPointCount, 1);
        return switch (style) {
            case OUTLINE -> {
                if (height == 0) yield cutoffAngle * radius / count;
                double circumference = cutoffAngle * radius;
                double wallArea = circumference * height;
                yield Math.sqrt((circumference + wallArea) / count);
            }
            case SURFACE -> {
                double discArea = cutoffAngle * 0.5 * radius * radius;
                double wallArea = cutoffAngle * radius * height;
                yield Math.sqrt((discArea + wallArea) / count);
            }
            case FILL -> Math.cbrt(cutoffAngle * 0.5 * radius * radius * height / count);
        };
    }

    @Override
    public boolean contains(Vector3d point) {
        double distSq = point.x * point.x + point.z * point.z;
        if (distSq > radius * radius) return false;
        if (height > 0) return point.y >= 0 && point.y <= height;
        return Math.abs(point.y) < EPSILON;
    }

    @Override
    public double getRadius() { return radius; }

    @Override
    public void setRadius(double radius) {
        this.radius = Math.max(radius, Shape.EPSILON);
        invalidate();
    }

    @Override
    public double getLength() { return 0; }

    @Override
    public void setLength(double length) { }

    @Override
    public double getWidth() { return 0; }

    @Override
    public void setWidth(double width) { }

    @Override
    public double getHeight() { return height; }

    @Override
    public void setHeight(double height) {
        this.height = Math.max(height, 0);
        invalidate();
    }

    @Override
    public Shape clone() {
        return this.copyTo(new Circle(radius, height));
    }

    @Override
    public String toString() {
        return "Circle{radius=" + radius + ", cutoffAngle=" + cutoffAngle + ", height=" + height + '}';
    }
}
